#server port
server:
  port: 80
zabbix:
  api:
    url: http://172.16.15.10/zabbix/
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frank
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: frank
      password: frank
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true