#server port
server:
  port: 8080
  compression:
    min-response-size:
  servlet:
    context-path: /api
zabbix:
  api:
    url: http://${ZABBIX_APIURL:172.19.0.5}:${ZABBIX_APIPORT:8080}/
  username: ${ZABBIXUSERNAME:Admin}
  password: ${ZABBIXPASSWORD:zabbix}
spring:
## ↓ ↓ ↓ ↓ ↓ ↓ MYSQL datasource ↓ ↓ ↓ ↓ ↓ ↓
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:172.17.0.1}:${DB_PORT:3306}/${DB_NAME:jit-security-aiops-server}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&tinyInt1isBit=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    connectionTimeout: 20000
    maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
## ↑ ↑ ↑ ↑ ↑ ↑ MYSQL datasource ↑ ↑ ↑ ↑ ↑ ↑

## ↓ ↓ ↓ ↓ ↓ ↓ DM datasource ↓ ↓ ↓ ↓ ↓ ↓
#  datasource:
#    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://172.16.15.10:5236/DAMENG?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#    username: JIT_SECURITY_AIOPS
#    password: JIT_SECURITY_AIOPS
#  jpa:
#    database-platform: org.hibernate.dialect.DmDialect
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: false
## ↑ ↑ ↑ ↑ ↑ ↑ DM datasource ↑ ↑ ↑ ↑ ↑ ↑
  jackson:
    time-zone: GMT+8
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
###################################
#--------------FTP配置-------------#
###################################
ftp:
  hostName: 172.19.0.1
  port: 21
  userName: jitutil
  passWord: dota&csjit3368
###################################
#--------------SFTP配置-------------#
###################################
sftp:
  hostName: 124.70.13.193
  port: 22
  userName: user1
  passWord: 111111
  remoteRootPath: /home/user1/upload
  timeOut: 3000
  useShow: 1
###################################
#--------------LOG配置-------------#
###################################
logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger:%L : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger:%L : %msg%n"
    level: info
  file:
    name: ./logs/JIT-security-AIOps-server.log
